### ISSUE TITLE
Implement To-Do List

### ISSUE THREAD

**Issue by jeonghyeonee** [jeonghyeonee/Memoriary#14]
This issue involves creating the To-Do List feature in the app, which allows users to list tasks, categorize them, and mark them as completed. Users can:

- [ ] Add and categorize tasks.
- [ ] Check off tasks when they are completed.
- [ ] Fragement Data Communication
- [ ] Calander View
